Repository tonnytg/42_minishell, pull requests merged in 2023-06, with the labels that each got.

#59 Fix/wrong commad
  includes/minishell.h
  srcs/commands.c
  srcs/commands/echo.c
  srcs/input.c
Labels: bug, high, Mandatory, theme_commands

#62 Signals base
  Makefile
  includes/minishell.h
  srcs/main.c
  srcs/signals/signals.c
Labels: feature, Mandatory, theme_signal

#66 fix: adjust result to similar original pwd
  srcs/commands/pwd.c
Labels: Mandatory, theme_history

#70 32 write tests for commands echo
  .github/workflows/cmd-echo-test.yml
  .github/workflows/cmd-exit-test.yml
  srcs/commands/echo.c
  srcs/input.c
Labels: need to test, review, theme_tests

#69 feat: #68 implement print exit code
  srcs/commands/echo.c
  srcs/input.c
Labels: feature, need to test, review, theme_commands

#74 Lexical1
  srcs/parser/syntax_analysis.c
Labels: feature, Mandatory, theme_commands

#76 Create a rule to valgring in Makefile
  Makefile
  srcs/commands/unset.c
Labels: feature, refact

#79 fix: #78 leak when empty command
  srcs/input.c
Labels: bug, leak, Mandatory, theme_commands

#80 feat(redirects): Create a redirect folder
  srcs/redirects/ft_pipe.c
Labels: carlos, feature, need to test, theme_redirects, in process

#81 71 engine token and syntax grammatic
  Makefile
  includes/minishell.h
  srcs/input.c
  srcs/main.c
  srcs/parser/build_struct_to_exec.c
  srcs/parser/syntax_analysis.c
  srcs/parser/token_analysis.c
Labels: theme_core

#83 fix: remove leaks
  srcs/parser/build_struct_to_exec.c
  srcs/parser/token_analysis.c
Labels: feature, theme_core

#84 71 engine token and syntax grammatic
  srcs/input.c
  srcs/main.c
  srcs/parser/build_struct_to_exec.c
  srcs/parser/token_analysis.c
Labels: feature, theme_core

#85 fix: solve segment fault caling cmds.list
  srcs/main.c
  srcs/parser/token_analysis.c
Labels: leak, theme_core
